language: python

python:
  - "3.6.3"

addons:
  chrome: stable
  postgresql: "9.5"

env:
  - DJANGO_SETTINGS_MODULE=application.settings

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver

install:
  - pip install -r requirements/dev.txt

cache:
  directories:
    - $HOME/.cache/pip

before_script:
  - createdb -E UTF-8 prognet_db
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - python manage.py test --noinput
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py radish features
